<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2019-08-12T05:40:37" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="Hello World Test" timestamp="2019-08-12T05:40:37" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="When page is opened" timestamp="2019-08-12T05:40:37" tests="1" failures="1" time="0">
    <testcase name="Hello World Test When page is opened Show สวัสดีชาวโลก" time="0" classname="Show สวัสดีชาวโลก">
      <failure message="cy.visit() failed trying to load:

http://localhost:4200/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  &gt; Error: connect ECONNREFUSED 127.0.0.1:4200

Common situations why this would fail:
  - you don&apos;t have internet access
  - you forgot to run / boot your web server
  - your web server isn&apos;t accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

Error: connect ECONNREFUSED 127.0.0.1:4200
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
" type="CypressError"><![CDATA[CypressError: cy.visit() failed trying to load:

http://localhost:4200/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:4200

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

Error: connect ECONNREFUSED 127.0.0.1:4200
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

    at Object.cypressErr (http://localhost:59913/__cypress/runner/cypress_runner.js:85348:11)
    at Object.throwErr (http://localhost:59913/__cypress/runner/cypress_runner.js:85303:18)
    at Object.throwErrByPath (http://localhost:59913/__cypress/runner/cypress_runner.js:85335:17)
    at http://localhost:59913/__cypress/runner/cypress_runner.js:73981:31
    at visitFailedByErr (http://localhost:59913/__cypress/runner/cypress_runner.js:73499:12)
    at http://localhost:59913/__cypress/runner/cypress_runner.js:73980:22
    at tryCatcher (http://localhost:59913/__cypress/runner/cypress_runner.js:118962:23)
    at Promise._settlePromiseFromHandler (http://localhost:59913/__cypress/runner/cypress_runner.js:116898:31)
    at Promise._settlePromise (http://localhost:59913/__cypress/runner/cypress_runner.js:116955:18)
    at Promise._settlePromise0 (http://localhost:59913/__cypress/runner/cypress_runner.js:117000:10)
    at Promise._settlePromises (http://localhost:59913/__cypress/runner/cypress_runner.js:117075:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:59913/__cypress/runner/cypress_runner.js:113687:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:59913/__cypress/runner/cypress_runner.js:113697:10)
    at Async.drainQueues (http://localhost:59913/__cypress/runner/cypress_runner.js:113571:14)]]></failure>
    </testcase>
  </testsuite>
</testsuites>